name: 'Terraform apply'
description: 'Terraform apply'
inputs:
  terraform_directory:
    description: 'Directory that holds Terraform code'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      shell: bash
      working-directory: ${{ inputs.terraform_directory }}
      run: terraform init

    - name: Download Terraform Plan
      uses: actions/download-artifact@v3
      with:
        name: tfplan

    - name: Terraform Apply
      shell: bash
      working-directory: ${{ inputs.terraform_directory }}
      run: terraform apply -auto-approve tfplan
